### ISSUE TITLE
Move curators.py to different repository

### ISSUE THREAD

**Issue by FunctionalMetatable** [scratch-advancedtopics/scratch-advancedtopics.github.io#10]
We shouldnt leave the curators.py file in the site repository
@ninjamar

**Comment by FunctionalMetatable** [comment]
@ninjamar could you also elevate members' permissions by letting them to edit the repository settings? i am planning to try a custom github bot instead of default github-actions

**Comment by ninjamar** [comment]
where would curators.py be? also how do i change the permissions? also what is the github bot?

**Comment by FunctionalMetatable** [comment]
> where would curators.py be? also how do i change the permissions? also what is the github bot?

curators.py would be in a repository like scratch-advancedtopics/update-curators-action

go into the repository settings and press "manage access", then just make everybody a repo admin

the github bot is a committer (instead of @github-actions) so we can have custom branding

**Comment by ninjamar** [comment]
> > where would curators.py be? also how do i change the permissions? also what is the github bot?
> 
> curators.py would be in a repository like scratch-advancedtopics/update-curators-action
> 
how would we the website fetch from the new repo?

**Comment by FunctionalMetatable** [comment]
> > > where would curators.py be? also how do i change the permissions? also what is the github bot?
> > 
> > 
> > curators.py would be in a repository like scratch-advancedtopics/update-curators-action
> 
> how would we the website fetch from the new repo?

umm curators.py is a github action script
we just use the uses field

**Comment by ninjamar** [comment]
> > > > where would curators.py be? also how do i change the permissions? also what is the github bot?
> > > 
> > > 
> > > curators.py would be in a repository like scratch-advancedtopics/update-curators-action
> > 
> > 
> > how would we the website fetch from the new repo?
> 
> umm curators.py is a github action script we just use the uses field.
> 
> if you want i can set it up

could you set it up?

**Comment by webdev03** [comment]
Isn't this already done?

**Comment by Dhuls-Scratch** [comment]
> Isn't this already done?

No. The action is still set to use the one in this repo (its offline anyways)
