### ISSUE TITLE
managers not listed

### ISSUE THREAD

**Issue by Dhuls-Scratch** [scratch-advancedtopics/scratch-advancedtopics.github.io#7]
only curators are listed. the 3 managers aren't.

**Comment by MystPi** [comment]
Ask @ninjamar. He can modify the GH action.

**Comment by ninjamar** [comment]
i broke it. itl be fixed later today

**Comment by ninjamar** [comment]
fixed i think. someone plz test

**Comment by ninjamar** [comment]
the file gets edited with the manager data but the website doesn't pick up the changes

**Comment by MystPi** [comment]
> the file gets edited with the manager data but the website doesn't pick up the changes

That's because you appended an array of managers to `members.json`. I'll have to update it to parse that array too.
